version: '3.3'

services:
  mongodb:
    image: mongo
    container_name: db
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_DOCKER_PORT
    networks:
      - fiappagamentos_default

  mongodb-express:
    image: mongo-express
    env_file: ./.env
    ports:
      - $MONGO_EXPRESS_LOCAL_PORT:$MONGO_EXPRESS_DOCKER_PORT
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_EXPRESS_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_EXPRESS_ADMINPASSWORD
      - ME_CONFIG_MONGODB_URL=$MONGO_EXPRESS_URL
    networks:
      - fiappagamentos_default

  app:
    depends_on:
      - mongodb
    build: ./
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgres:$POSTGRES_DOCKER_PORT/$POSTGRES_DATABASE",
        "spring.datasource.username" : "$POSTGRES_ROOT_USER",
        "spring.datasource.password" : "$POSTGRES_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.show-sql" : true,
        "spring.datasource.initialization-mode" : "always",
        "spring.datasource.initialize" : true,
        "spring.datasource.continue-on-error": true,
        "spring.jpa.hibernate.ddl-auto":"update",
        "server.port" : "$SPRING_LOCAL_PORT",
        "pedido.service.url": "$PEDIDO_SERVICE_URL"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - fiappagamentos_default

networks:
  fiappagamentos_default:
    driver: bridge
