# Create a deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apl
spec:
  selector:
    matchLabels:
      app: apl
  replicas: 1
  template:
    metadata:
#      annotations:
#        eks.amazonaws.com/role-arn: arn:aws:iam::231670762225:role/my-app-service-account
      labels:
        app: apl
    spec:
      containers:
        - name: apl
          image: fiappagamentos/fiappagamentos:v1
          imagePullPolicy: "Always"
          env:
            - name: spring.datasource.initialize
              valueFrom: 
                configMapKeyRef:
                  name: apl-config
                  key: DATASOURCE_INITIALIZE
            - name: spring.jpa.hibernate.ddl-auto
              valueFrom: 
                configMapKeyRef:
                  name: apl-config
                  key: HIBERNATE_DDL_AUTO
            - name: pedido.service.url
              valueFrom:
                configMapKeyRef:
                  name: apl-config
                  key: PEDIDO_URL
            - name: spring.data.mongodb.uri
              valueFrom:
                configMapKeyRef:
                  name: apl-config
                  key: MONGO_URI
            - name: spring.data.mongodb.database
              valueFrom:
                configMapKeyRef:
                  name: apl-config
                  key: MONGO_DATABASE
            - name: server.port
              value: '9090'
          ports:
            - containerPort: 9090