# Create a service
kind: Service
apiVersion: v1
metadata:
  name: apl-pagamentos
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::813173347981:role/eks-eks-nodes"
spec:
  selector:
    app: apl-pagamentos
  ports:
    - name: apl-pagamentos
      targetPort: 9090
      port: 9090
  type: LoadBalancer
